services:
  backend:
    environment:
      - LEGACY_USE_DEBUG=1
    volumes:
      - ./server:/home/legacy-use-mgmt/server
      - ./pyproject.toml:/home/legacy-use-mgmt/pyproject.toml
      - ./uv.lock:/home/legacy-use-mgmt/uv.lock

  frontend:
    environment:
      - LEGACY_USE_DEBUG=1
    volumes:
      - ./app:/web/app
      - ./public:/web/public
      - ./tsconfig.json:/web/tsconfig.json
      - ./vite.config.js:/web/vite.config.js
      - ./orval.config.ts:/web/orval.config.ts
      - ./index.html:/web/index.html
