"""add rdp params

Revision ID: 04ea171080e4
Revises: 0a7bc5c94ccb
Create Date: 2025-08-10 21:25:23.263239

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from server.migrations.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision: str = '04ea171080e4'
down_revision: Union[str, None] = '0a7bc5c94ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@for_each_tenant_schema
def upgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'targets',
        sa.Column('rdp_params', sa.String(), nullable=True),
        schema='tenant_default',
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'rdp_params', schema='tenant_default')
    # ### end Alembic commands ###
