"""Initial migration

Revision ID: f4ac82882dc0
Revises:
Create Date: 2025-02-28 17:52:46.723805

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f4ac82882dc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
