"""add_tenant_settings_table

Revision ID: f705ed66700e
Revises: 0a7bc5c94ccb
Create Date: 2025-08-01 18:39:42.239725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from server.migrations.tenant import for_each_tenant_schema


# revision identifiers, used by Alembic.
revision: str = 'f705ed66700e'
down_revision: Union[str, None] = '0a7bc5c94ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@for_each_tenant_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'settings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('key', sa.String(length=256), nullable=False),
        sa.Column('value', sa.String(length=4096), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema=schema,
    )
    op.create_index(
        op.f('ix_settings_key'), 'settings', ['key'], unique=False, schema=schema
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings', schema=schema)
    op.drop_table('settings', schema=schema)
    # ### end Alembic commands ###
